### PR TITLE
Add aom and libheif to 'web' group dependencies for AVIF support

### LINKED ISSUE #13: Proposal: move aom and libheif to "web" dependencies
I'm (slowly) setting up the infrastructure to ensure the aom+libheif+libvips combo is safe (fuzz, leak and regression tested) for binary distribution and therefore allow the prebuilt binaries provided by sharp to read and write AVIF files. See https://github.com/lovell/sharp/issues/2289 for more context.

Can anyone think of a reason not to move these?

### PR DESCRIPTION
**Pull request by lovell**
Resolves #13

### CODE REVIEW

**Comment by lovell** [comment]
@kleisauke Thanks for adding the `libheif.pc` patch. (I finally managed to get libheif's CI to pass with that change.)

**Comment by kleisauke** [comment]
Great! I'm currently debugging a segfault in SSE2 code that happens on Windows i686 in combination with GCC (v10.2 and 9.3) and aom (master and v2.0.0). The binaries produced by LLVM works without any problems.

<details>
 <summary>Details</summary>

```
Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
eax=0d5d7e70 ebx=00000072 ecx=0321e4f8 edx=00000630 esi=0d5d7e70 edi=00000000
eip=6a450370 esp=0321e460 ebp=0321e460 iopl=0         nv up ei pl nz na pe nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010206
libvips_42!aom_dc_left_predictor_8x16_sse2+0x10:
6a450370 660f6f01        movdqa  xmm0,xmmword ptr [ecx] ds:002b:0321e4f8=72727272727272727272727272727272
```
</details>

I suspect this is an assembler bug, I'm now trying to compile GCC v10.2 with binutils v2.35.1 as the binutils provided by MXE is old (v2.28, released on 2017-03-06). If that doesn't work, I think we need to disable the SIMD optimizations for i686 (i.e. compile with `-DAOM_TARGET_CPU=generic`).

**Comment by lovell** [comment]
Did you see aom's `-DENABLE_SSE2=0` flag? https://aomedia.googlesource.com/aom/+/master/build/cmake/cpu.cmake#70

**Comment by kleisauke** [comment]
Ah, I missed that. Upgrading binutils to the latest version didn't help, unfortunately. I disabled SSE2 with commit 050e4eb but it seems that this also disables the remaining optimizations (possible due to that `disable_remaining_flavors` flag).

i686 now almost passes the test suite, it fails with the last `heifsave` test here:
https://github.com/libvips/libvips/pull/1845/files#diff-ad635814429f3e0cbd2aa94557b49443R1083-R1090
```
Failed to initialize encoder: Memory allocation error
```
(this needs a patch for libheif to improve the error reporting, see: 21ae186)

**Comment by kleisauke** [comment]
The SSE2 segfault turns out to be a stack alignment bug, commit https://github.com/libvips/build-win64-mxe/pull/16/commits/755c615cf3e18444364c8048c4e0491347c0b292 adds a patch to fix this. I also incorporated patches from dav1d/webp with commit https://github.com/libvips/build-win64-mxe/pull/16/commits/afdf49bf586c5c919ad237bc74d9685aec0bac2e and backported a security fix with commit https://github.com/libvips/build-win64-mxe/pull/16/commits/36bfc16ce65f5663923e1be1de5c99c02a042199.

Windows x86 still has a OOM failure on the `heifsave` test suite, I'm not sure if there is an easy way to fix that. x64 passes the test suite without problems. I think this is ready to be included for the libvips 8.10.2 binaries, are you OK with that?

**Comment by lovell** [comment]
Fantastic, thank you Kleis, I'll let you press the big green merge button when you're ready.

**Comment by kleisauke** [comment]
For the record, test suite currently fails on Windows ARM64 when checking the absolute difference between loading and saving the same AVIF image. I could also reproduce this on the command line, when I do this:
```bash
$ vips copy avif-orientation-6.avif x2.avif[compression=av1]
```

Output: https://t0.nl/x2.avif
Expected output: https://github.com/kleisauke/libvips/blob/testsuite-avif/test/test-suite/images/avif-orientation-6.avif

Anyway, it works fine on Linux ARM64 (see https://github.com/libvips/libvips/pull/1845/commits/c4f9bdcea35d42e2797b4bfeb2951c5eb1df588a and [Travis build](https://travis-ci.org/github/libvips/libvips/jobs/734243492)), so this is ready for merging.

**Review by kleisauke — APPROVED** [review]

**Pull request merged**
